---
title: "p8105_hw2_ab6169"
author: "Amrutha Banda"
date: "2025-09-25"
output: html_document
---

## Problem 1

First, I load my libraries
```{r setup, include=FALSE}
library(tidyverse)
library(janitor) 
library(readxl)
```

Cleaning the `pols-month.csv` data
```{r message = FALSE}
pols_df= 
  read_csv("data_hw2/pols-month.csv", na = c("NA", ".", "")) |>
separate(mon, into = c("year", "month", "day"), sep = "-") |>
mutate(
  year = as.integer(year),
  month = as.integer(month),
  month = month.name[month],
  president = ifelse(prez_gop == 1, "gop", "dem")) |>

  select(-day, -prez_gop, -prez_dem)
```


Cleaning the `snp.csv` data

```{r message = FALSE}
snp_df= 
  read_csv("data_hw2/snp.csv", na = c("NA", ".", ""))|>
  separate(date, into = c("month", "day", "year"), sep = "/") |>
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    month = month.name[month]) |>
  select(year, month, close) |>
  arrange(year, month)
```

Cleaning the `unemployment.csv` data



```{r message = FALSE}
unemployment_df= 
  read_csv("data_hw2/unemployment.csv", na = c("NA", ".", "")) |>
pivot_longer(
    cols = Jan:Dec,      
    names_to = "month",
    values_to = "unemployment"
  ) |>
  mutate(
    month = case_match(
      month,
      "Jan" ~ "January",
      "Feb" ~ "February",
      "Mar" ~ "March",
      "Apr" ~ "April",
      "May" ~ "May",
      "Jun" ~ "June",
      "Jul" ~ "July",
      "Aug" ~ "August",
      "Sep" ~ "September",
      "Oct" ~ "October",
      "Nov" ~ "November",
      "Dec" ~ "December") ) |> 
  rename(year = Year) |>
  select(year, month, unemployment)
```

Merging `snp.csv` and `pol-month.csv` and `unemployment.csv`
```{r message = FALSE}
merged_df= 
pols_df |>
  left_join(snp_df, by = c("year", "month")) |>
  left_join(unemployment_df, by = c("year", "month"))
```

Write-Up: 

## Problem 2 

```{r}
mr_trash_df =
  read_excel("data_hw2/trashwheeldata.xlsx", 
             sheet= "Mr. Trash Wheel",
             skip = 1, na= c("NA", ".", "")) |> 
janitor:: clean_names() |> 
drop_na(dumpster) |> 
select(-x15, -x16) |>
 mutate(
  year = as.integer(year),
  sports_balls = as.integer(round(sports_balls)),
  wheel= "Mr.Trash Wheel"
)

prof_trash_df =
  read_excel("data_hw2/trashwheeldata.xlsx",
             sheet = "Professor Trash Wheel",
             na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  drop_na(dumpster) |> 
  mutate(
    year = as.integer(year),
    wheel = "Professor Trash Wheel") 


gwynnda_df =
  read_excel("data_hw2/trashwheeldata.xlsx",
             sheet = "Gwynnda Trash Wheel",na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  drop_na(dumpster) |> 
  drop_na(wrappers) |> 
  mutate(
    year = as.integer(year),
    wheel = "Gwynnda Trash Wheel") 

trash_wheel_df =
  bind_rows(mr_trash_df, prof_trash_df, gwynnda_df) |>
  janitor:: clean_names() |>
  relocate(wheel, year, month)

```

Writeup

